config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
 get '/home', to: 'pages#home'
 
 # get '/recipes', to: 'recipes#index'
 # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
 # post '/recipes', to: 'recipes#create', as: 'create_recipe'
 # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
 # patch '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
 # get '/recipes/:id', to: 'recipes#show', as: 'show_recipe'
 # delete '/recipes/:id', to: 'recipes#destroy', as: 'delete_recipe'
  
 resources :recipes do 
   member do
     post 'like'
   end
 end
  
 resources :chefs, except: [:new, :destroy]
 
 get '/register', to: 'chefs#new'
 
 get '/login', to: 'logins#new'
 post '/login', to: 'logins#create'
 get '/logout/', to: 'logins#destroy'
 
 resources :styles, only: [:new, :create, :show, :index]
 resources :ingredients, only: [:new, :create, :show, :index]
 
end
 

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2>This is the exercise for Professional Ruby on Rails Develepor Course on Udemy</h2>
  <%= link_to "Sign Up Now", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-2">
    <h3 class="midrow">
      View Chefs
    </h3>
    <p><%= link_to "Browse Chef Listings", chefs_path, class: "btn btn-warning btn-small"%> </p>
  </div>
    <div class="col-lg-2">
    <h3 class="midrow">
      View Recipes
    </h3>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small"%> </p>
  </div>
  <div class="col-lg-2">
    <h3 class="midrow">
      View Styles
    </h3>
    <p><%= link_to "Browse Style Listings", '', class: "btn btn-warning btn-small"%> </p>
  </div>
  <div class="col-lg-3">
    <h3 class="midrow">
      View Ingredients
    </h3>
    <p><%= link_to "Browse Ingredients Listings", '', class: "btn btn-warning btn-small"%> </p>
  </div>
</div>